/**
 * This file is generated by Skaryna
 */

import { Skaryna, TReactComponent } from "../skaryna/lib/generator/skaryna";
import * as React from "react";
import * as path from "path";
import Index from "./index";

import Page from "./_layouts/page";
import Post from "./_layouts/post";
import Head from "./_includes/head";
import Header from "./_includes/header";
import Footer from "./_includes/footer";

const page: TReactComponent = Page;

Skaryna
    .init(__dirname, path.join(__dirname, "_site"))
    .then(async (skaryna: Skaryna) => {
        // register layouts
        skaryna.registerLayout("page", Page);
        skaryna.registerLayout("post", Post);

        // register includes
        await skaryna.buildSite(Index, Head);
    });

